version: "3.8"

services:
  users_db:
    image: postgres
    environment:
      - POSTGRES_DB=users-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses='*'
    networks:
      - backend

  api:
    build:
      context: .
    command: sh -c "npm run start:prod"
    environment:
      - DB_HOST=users_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - USERS_DATABASE_URL=postgres://postgres:password@users_db:5432/users-db
      - JWT_SECRET=some-jwt-secret
    ports:
      - "3000:3000"
    depends_on:
      - users_db
    networks:
      - backend

networks:
  backend:
